### ISSUE TITLE
PowerPC, MIPS and NetBSD problem

### ISSUE THREAD

**Issue by Trojan295** [passcod/notify#155]
Hello,

I'm trying to compile notify 4.0.3 on a few different environments and looks it's failing on some (https://travis-ci.org/jedisct1/flowgger/builds/351310716).

For NetBSD (x86_64-unknown-netbsd) it looks like an issue with a dependency (https://github.com/alexcrichton/filetime):
```
error[E0425]: cannot find value `utimensat` in module `libc`
 --> /cargo/registry/src/github.com-1ecc6299db9ec823/filetime-0.1.15/src/unix/utimensat.rs:8:45
  |
8 |     super::utimensat(p, atime, mtime, libc::utimensat, 0)
  |                                             ^^^^^^^^^ did you mean `futimens`?
help: possible candidate is found in another module, you can import it into scope
  |
1 | use imp::utimensat;
  |
```

mips, powerpc and s390x, could be failing due to some old dependencies (mio 0.5.1 and nix 0.5.1), which didn't support such architectures (https://docs.rs/crate/nix/0.5.1/source/src/sys/syscall.rs):
```
error[E0432]: unresolved import `self::arch`
 --> /cargo/registry/src/github.com-1ecc6299db9ec823/nix-0.5.1/src/sys/syscall.rs:5:15
  |
5 | pub use self::arch::*;
  |               ^^^^ Could not find `arch` in `self`
error[E0433]: failed to resolve. Use of undeclared type or module `cpuset_attribs`
   --> /cargo/registry/src/github.com-1ecc6299db9ec823/nix-0.5.1/src/sched.rs:118:25
    |
118 |     cpu_mask: [CpuMask; cpuset_attribs::CPU_SETSIZE/cpuset_attribs::CPU_MASK_BITS]
    |                         ^^^^^^^^^^^^^^ Use of undeclared type or module `cpuset_attribs`
```

**Comment by passcod** [comment]
Firstly, thanks for trying on such architectures! v5 is going to be built on a wider range of archs, but up until then I'm mostly relying on people like you testing it out.

IIRC, upgrading mio requires some pretty large changes, so I didn't elect to do it on the v4 branch. If you want to take a crack at it, I'd welcome any PR, though.

For filetime, I think this is the same issue? https://github.com/alexcrichton/filetime/issues/19 It seems it's a libc issue instead. Try filing with them?

**Comment by Trojan295** [comment]
OK, the problem with NetBSD is solved, we had libc locked to 0.2.31 and after an update to 0.2.39 the issue disappeared.

I will see what I can do with this update of mio, although I'm not so experienced with Rust.. but willing to learn! :)

**Comment by passcod** [comment]
This will be fixed when v5 releases due to it using a newer mio.

**Comment by passcod** [comment]
I believe this is now fixed with #162 (in 4.0.6)
